### ISSUE TITLE
What! Really? What's going on?

### ISSUE THREAD

**Issue by seamustuohy** [opentechinstitute/luci#2]
What are you doing forking LuCI's code base? I am so intrigued.....

**Comment by dismantl** [comment]
We're forking LuCI so we can make modifications to the upgrade functionality (see https://github.com/opentechinstitute/luci/pull/1 and https://github.com/opentechinstitute/luci-commotion/pull/454). I wrote a new upgrade utility that let's you bundle images with upgrade scripts to run before the new image is flashed, and sign the upgrade bundle with Serval keys.

**Comment by seamustuohy** [comment]
Awesome!
